# -*- coding: utf-8 -*-
"""Semantique.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vK73ld0BB9qWmmCVv_xnxxKDbdhxJlG
"""

!pip install datasets tqdm

from datasets import load_dataset
import re
import random
import json
from tqdm import tqdm

def fast_collect():
    poly_words = [
        "éclair", "patron", "règle", "rose", "bouton", "feuille", "chemise",
        "glace", "coup", "jumelle", "cœur", "maison", "vague", "fond",
        "rayon", "nœud", "verre", "lettre", "mousse", "corps", "carte",
        "poste", "ordre", "temps", "parti", "classe", "vol", "grève", "feu"
    ]

    neutral_words = ["café", "orange", "kiwi", "pêche", "avocat"]
    all_words = list(set(poly_words + neutral_words))

    # 每个词只要 30 句（推荐）
    limit = 30
    corpus = {w: [] for w in all_words}

    print("Loading dataset (streaming)...")

    dataset = load_dataset(
        "wikimedia/wikipedia",
        "20231101.fr",
        split="train",
        streaming=True
    )

    # ⭐ 加速关键：只看前 30000 条文章
    max_docs = 30000

    # tqdm 只显示进度，不影响速度
    pbar = tqdm(total=max_docs)

    for i, entry in enumerate(dataset):

        if i >= max_docs:
            break

        text = entry["text"].replace("\n", " ")

        # ⭐ 加速关键：只随机取部分句子（不是全扫）
        sentences = re.split(r'(?<=[.!?])\s+', text)
        sentences = random.sample(sentences, min(len(sentences), 10))

        for sn in sentences:
            if len(sn) < 40 or len(sn) > 300:
                continue

            for word in all_words:

                # 已收集够就跳过
                if len(corpus[word]) >= limit:
                    continue

                # 词匹配
                if re.search(rf'\b{word}\b', sn, re.IGNORECASE):
                    corpus[word].append(sn)

        pbar.update(1)

        # ⭐ 如果全部词都够了 → 直接结束
        if all(len(corpus[w]) >= limit for w in all_words):
            break

    pbar.close()

    with open("fast_corpus.json", "w", encoding="utf-8") as f:
        json.dump(corpus, f, ensure_ascii=False, indent=2)

    print("Done!")

if __name__ == "__main__":
    fast_collect()

import json

# 1. 读取文件
with open("fast_corpus.json", "r", encoding="utf-8") as f:
    data = json.load(f)

print("=== Corpus Statistics ===\n")

# 2. 遍历每个词
for word, sentences in data.items():

    lengths = [len(s) for s in sentences]

    print(f"WORD: {word}")
    print(f"  number of sentences: {len(sentences)}")

    if len(sentences) > 0:
        print(f"  avg length: {sum(lengths)/len(lengths):.1f}")
        print(f"  min length: {min(lengths)}")
        print(f"  max length: {max(lengths)}")

    print("-" * 40)
